import psycopg2

# WORKING WITH DATABASES.
# LEARN HOW TO MAN, AND PERFORM SOME CRUD(CREATE, READ, UPDATE, DELETE)
'''
HOW DO DATA GET RESTORED IN A DATABASE.

TABLE(rows, columns)
THESE MUST BE STRUCTURED. (())
30. 
ADDRES, USERS, ACCOUNT_DATAILS, EMPLOYEES, MANAGERS

'''
# RELATIONAL DATABASE. (RDBMS)
